# on Windows, put this config file at %APPDATA%/Roaming/alacritty/alacritty.toml
# see also:
# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty/blob/master/docs/features.md

# note that I can't make a symlink between %APPDATA$ and /some/wsl/path
#   so this is just a static copy that needs continual updating...

shell = "C:/Windows/System32/wsl.exe"
working_directory = "C:/Users/jkwon/Desktop/"
live_config_reload = true

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_title = true
padding = { x = 8, y = 10 }
opacity = 1.5
# for terminal screenshots for demos (don't forget to disable startup_mode too):
# dimensions = { columns = 80, lines = 25 }

[font]
normal = { family = "Source Code Pro", style = "Regular" } # or cascadia code
size = 10

[keyboard]
bindings = [
	{ key = "Q" , mods = "Control | Shift" , action = "Quit" } ,
	{ key = "Tab" , mods = "Control" , chars = "\u001b[27;5;9~" } ,
	{ key = "Tab" , mods = "Control | Shift" , chars = "\u001b[27;6;9~" } ,
	{ key = " " , mods = "Control | Shift" , action = "ToggleViMode" } ,
]
